const CityData = [
    { value: 'Abidjan', label: 'Abidjan' },
    { value: 'Accra', label: 'Accra' },
    { value: 'Addis Ababa', label: 'Addis Ababa' },
    { value: 'Algiers', label: 'Algiers' },
    { value: 'Asmara', label: 'Asmara' },
    { value: 'Bamako', label: 'Bamako' },
    { value: 'Bangui', label: 'Bangui' },
    { value: 'Banjul', label: 'Banjul' },
    { value: 'Bissau', label: 'Bissau' },
    { value: 'Blantyre', label: 'Blantyre' },
    { value: 'Brazzaville', label: 'Brazzaville' },
    { value: 'Bujambura', label: 'Bujambura' },
    { value: 'Cairo', label: 'Cairo' },
    { value: 'Casablanca', label: 'Casablanca' },
    { value: 'Ceuta', label: 'Ceuta' },
    { value: 'Conakry', label: 'Conakry' },
    { value: 'Dakar', label: 'Dakar' },
    { value: 'Dar es Salaam', label: 'Dar es Salaam' },
    { value: 'Djibouti', label: 'Djibouti' },
    { value: 'Douala', label: 'Douala' },
    { value: 'El Aaiun', label: 'El Aaiun' },
    { value: 'FreeTown', label: 'FreeTown' },
    { value: 'Gaborone', label: 'Gaborone' },
    { value: 'Harare', label: 'Harare' },
    { value: 'Johannesburg', label: 'Johannesburg' },
    { value: 'Juba', label: 'Juba' },
    { value: 'Kampala', label: 'Kampala' },
    { value: 'Khartoum', label: 'Khartoum' },
    { value: 'Kigali', label: 'Kigali' },
    { value: 'Kinshasa', label: 'Kinshasa' },
    { value: 'Lagos', label: 'Lagos' },
    { value: 'Libreville', label: 'Libreville' },
    { value: 'Lome', label: 'Lome' },
    { value: 'Luanda', label: 'Luanda' },
    { value: 'Lubumbashi', label: 'Lubumbashi' },
    { value: 'Lusaka', label: 'Lusaka' },
    { value: 'Malabo', label: 'Malabo' },
    { value: 'Maputo', label: 'Maputo' },
    { value: 'Maseru', label: 'Maseru' },
    { value: 'Mbabane', label: 'Mbabane' },
    { value: 'Mogadishu', label: 'Mogadishu' },
    { value: 'Monrovia', label: 'Monrovia' },
    { value: 'Nairobi', label: 'Nairobi' },
    { value: 'Ndjamena', label: 'Ndjamena' },
    { value: 'Naimey', label: 'Naimey' },
    { value: 'Nouakchott', label: 'Nouakchott' },
    { value: 'Ouagadougou', label: 'Ouagadougou' },
    { value: 'Porto-Novo', label: 'Porto-Novo' },
    { value: 'Sao-Tome', label: 'Sao-Tome' },
    { value: 'Tripoli', label: 'Tripoli' },
    { value: 'Tunis', label: 'Tunis' },
    { value: 'Windhoek', label: 'Windhoek' },
    // Add more cities here...
  ];
  
  export default CityData;
  